<img src = "https://drive.google.com/uc?export=view&id=1K9OCVYN1o-SI5c11HV1z2R-ruaN4IQet" alt = "Encabezado MLDS unidad 1" width = "100%">  </img>

# **SQL y Pandas**
---

En este notebook veremos cómo podemos integrar bases de datos SQL con `pandas`.

Recuerde que `pandas` es una librería que nos permite la manipulación de datos tabulares en _Python_ en forma de `DataFrames`. Este tipo de datos resulta ser bastante cercano a las tablas de SQL, por lo cual son dos herramientas altamente compatibles.

Para este ejemplo, usaremos la base de datos en [neon.tech](https://neon.tech/):

In [ ]:
!pip install psycopg2
!pip install sqlalchemy

In [ ]:
import psycopg2
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

Debe ingresar a continuación la URL que te aparece en [neon.tech](https://neon.tech/). En las últimas versiones de alchemy se debe cambir `postgres` en la url  por `postgresql`:

In [ ]:
PG_STRING =  'postgresql://jfcaromo:pIv7KNxE4dTF@ep-proud-silence-76442732.us-east-2.aws.neon.tech/Database2?sslmode=require'

Para este ejemplo usaremos `sqlalchemy`, el cual es un [object-relational mapping (ORM)](https://en.wikipedia.org/wiki/Object%E2%80%93relational_mapping) para _Python_ que soporta distintos motores de bases de datos.

`sqlalchemy` permite mantener un registro programático (orientado a objetos) de los esquemas de las tablas y las consultas. Con esto conseguimos una mejor validación de tipos e integración con distintas aplicaciones.

Puede ver más información sobre `sqlalchemy` en [éste enlace](https://www.sqlalchemy.org/library.html).

En este caso, usaremos un `engine` de `sqlalchemy` como objecto de conexión para la integración con `pandas`.

> **Nota**: pandas puede usar cualquier objeto de conexión de cualquier driver de base de datos (`psycopg2`, `sqlite3`, entre otros), sin embargo, `sqlalchemy` valida tipos y suele ser más útil para la integración.

In [ ]:
engine = create_engine(PG_STRING,  echo=True)

## **1. Escritura**
---

Para la escritura, vamos a usar la función `df.to_sql` de pandas, primero vamos a cargar un [conjunto de datos](https://www.kaggle.com/datasets/kevinmorgado/us-energy-generation-2001-2022) sobre el consumo de energía de distintas fuentes en Estados Unidos:

In [ ]:
df_consumo = pd.read_parquet(
        "https://drive.google.com/uc?export=view&id=1dMw4CwrgEZEWJylueaiBNe_tKo5ihWXA"
        )
df_estados = pd.read_parquet(
        "https://drive.google.com/uc?export=view&id=1b7BnUTgVOCljKJmNaVAEyldsvPF25Or_"
        )

Veamos columnas y tipos de cada dataframe:

In [ ]:
df_consumo.info()

In [ ]:
df_estados.info()

Ahora, vamos a cargar estas tablas dentro de la base de datos de _PostgreSQL_:

In [ ]:
df_consumo.to_sql(
        name="consumo",
        con=engine,
        if_exists="replace",
        index=False,
        method="multi"
        )

In [ ]:
df_estados.to_sql(
        name="estados",
        con=engine,
        if_exists="replace",
        index=False,
        method="multi"
        )

Debemos especificar:

* `name`: nombre de la tabla.
* `con`: objeto de conexión.
* `if_exists`: específica que se debe hacer cuando la tabla ya existe, puede ser `'fail'` (error), `'replace'` (reemplaza la tabla) o `'append'` (agrega los valores al final de la tabla).
* `index`: específica si se guarda el índice como una columna.
* `method`: método para guardar los registros, puede ser `None` (registro a registro) o `'multi'` (batch o varios registros al tiempo).

## **2. Lectura**
---

Con el método `pd.read_sql` podemos extraer una consulta de SQL en forma de dataframe, veamos un ejemplo:

In [ ]:
query = text("""
SELECT
    anio,
    AVG(megawatthour) AS promedio_energia
FROM
    consumo
GROUP BY
    anio
HAVING
    anio >= 2020
;
""")

In [ ]:
with engine.connect() as conn:
    data = pd.read_sql(query, conn)
data

De esta forma, puede realizar operaciones costosas de forma persistida (disco) desde SQL y hacer depuraciones finales desde pandas (memoria).

Por ejemplo, la siguiente consulta calcula el promedio de energía por estado y por año:

In [ ]:
query = text("""
SELECT
    l.anio AS anio,
    r.nombre_estado AS estado,
    AVG(l.megawatthour) AS promedio_energia
FROM
    consumo AS l
INNER JOIN
    estados AS r
ON
    l.codigo_estado = r.codigo_estado
GROUP BY
    anio, estado
;
""")

In [ ]:
with engine.connect() as conn:
    data = pd.read_sql(query, conn)
data

In [ ]:
data.head()

## **3. Recursos Adicionales**
---

* [Neon tech y alchemy](https://neon.tech/docs/guides/sqlalchemy).
* [Pandas y SQL](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_sql.html)

## **4. Créditos**
---

**Profesor**

- [Jorge E. Camargo, PhD](https://dis.unal.edu.co/~jecamargom/)

**Diseño, desarrollo del notebook y material audiovisual**

- [Juan S. Lara MSc](https://www.linkedin.com/in/juan-sebastian-lara-ramirez-43570a214/)

**Universidad Nacional de Colombia** - *Facultad de Ingeniería*